#!/usr/bin/env bash

LABEL="<span font='FontAwesome' size='large'>⇅ </span>"
DT=3
ONE_KB=1024
ONE_MB=$(echo "${ONE_KB}*1024" | bc -l)
TEN_MB=$(echo "${ONE_MB}*10" | bc -l)
OHD_MB=$(echo "${TEN_MB}*10" | bc -l)

function FormatNumber() {
  if [[ "${1}" -ge "${OHD_MB}" ]]; then
    echo $(echo "scale=0;${1}/${ONE_MB}" | bc -l)"mb"
  elif [[ "${1}" -ge "${TEN_MB}" ]]; then
    echo $(echo "scale=1;${1}/${ONE_MB}" | bc -l)"mb"
  elif [[ "${1}" -ge "${ONE_MB}" ]]; then
    echo $(echo "scale=2;${1}/${ONE_MB}" | bc -l)"mb"
  elif [[ "${1}" -ge "${ONE_KB}" ]]; then
    echo $(echo "scale=0;${1}/${ONE_KB}" | bc -l)"kb"
  else
    echo "${1}""b"
  fi
}

IFACE="$(ip route | awk '/^default via/ {print $5; exit}')"
RX_OLD=0
TX_OLD=0

while true; do
  IFACE_STATS="$(grep ${IFACE} /proc/net/dev | cut -d: -f2)"

  if [[ "${IFACE_STATS}" = "" ]]; then
    exit
  fi

  RX_CUR=$(echo "${IFACE_STATS}" | awk '{print $1}')
  TX_CUR=$(echo "${IFACE_STATS}" | awk '{print $9}')

  if [[ "${TX_OLD}" != "0" ]] && [[ "${RX_OLD}" != "0" ]]; then
    RX_DIFF=$(echo "scale=0;(${RX_CUR} - ${RX_OLD})/${DT}" | bc -l)
    TX_DIFF=$(echo "scale=0;(${TX_CUR} - ${TX_OLD})/${DT}" | bc -l)

    RX_USAGE=$(FormatNumber "${RX_DIFF}")
    TX_USAGE=$(FormatNumber "${TX_DIFF}")

    echo "${LABEL}${RX_USAGE} : ${TX_USAGE}"
  else
    echo "${LABEL}? : ?"
  fi

  RX_OLD=${RX_CUR}
  TX_OLD=${TX_CUR}
  sleep ${DT}
done
