#!/usr/bin/env zsh

# selecting the line to display from the input
# if there is the playing status, it will be selected
# if none is playing, the spotify will be selected
# if none is playing and there is no spotify, the last one will be selected
select_line() {
	local statuses=("${(@f)${1}}")
	local selected=""
	local picked_player

	for line in "${statuses[@]}"; do
		local player=$(echo $line | cut -d';' -f1)
		if [[ $(echo $line | cut -d';' -f2) == 'playing' ]]; then
			selected=$line
			break
		elif [[ $player == 'spotify' ]]; then
			selected=$line
			picked_player=$player
		fi
	done
	if [[ -z $selected ]]; then
		selected=$line
	fi
	echo "${selected}"
}

format_output() {
	# create an array of strings separated by a newline
	INP=$(cat)
	INPUT=$(select_line "${INP}")
	if [[ -z $INPUT ]]; then
		echo "<span font='FontAwesome'></span> No media playing"
		exit 0
	fi
	PLAYER=$(echo $INPUT | awk -F ';' '{print $1}')
	case $PLAYER in
		"spotify")
			PLAYER="<span font='FontAwesome'></span>"
			;;
		"mpv")
			PLAYER="<span font='FontAwesome'></span>"
			;;
		"firefox")
			PLAYER="<span font='FontAwesome'></span>"
			;;
		*)
			PLAYER="<span font='FontAwesome'></span>"
			;;
	esac

	STATUS=$(echo $INPUT | awk -F ';' '{print $2}')
	case $STATUS in
		"playing")
			STATUS="<span font='FontAwesome'></span>"
			;;
		"paused")
			STATUS="<span font='FontAwesome'></span>"
			;;
		"stopped")
			STATUS="<span font='FontAwesome'></span>"
			;;
		*)
			STATUS="<span font='FontAwesome'></span>"
			;;
	esac

	ARTIST=$(echo $INPUT | awk -F ';' '{print $3}')
	TITLE=$(echo $INPUT | awk -F ';' '{print $4}')

	echo "$PLAYER $STATUS $ARTIST - $TITLE"
}

playerctl -a --format '{{lc(playerName)}};{{lc(status)}};{{artist}};{{trunc(title, 20)}}' metadata | format_output
