local pack = require "fw.pack"
pack.add { "nvim-lua/plenary.nvim" }

require "plugins.tmux"
require "plugins.autosession"
require "plugins.snacks"
require "plugins.git"
require "plugins.treesitter"
require "plugins.lspsetup"
require "plugins.linter"
require "plugins.debug"
require "plugins.autoformat"
require "plugins.setuplangs"
require "plugins.testing"
require "plugins.ui"
require "plugins.completions"
require "plugins.editor"
require "plugins.diagnostics"
require "plugins.chat"
