# Global properties
#
# The top properties below are applied to every block, but can be overridden.
separator=false
markup=pango
separator_block_width=0

[Weather]
command=~/.config/i3/scripts/openweather-city
interval=1800

[simple-2]
full_text=    

[player_status]
command=~/.config/i3/scripts/player-status
interval=1
min_width=1050
align=center
background=#3b4a61

[simple-2]
full_text=  
background=#3b4a61

[simple-2]
full_text=  
background=#292e42
min_width=20

[net]
label=  
command=echo "$(iwconfig wlan0 | grep -Po '(?<=ESSID:\")[^\"]*')"
interval=30
background=#292e42

[simple-2]
full_text= 
background=#292e42
min_width=10

[bandwidth]
command=~/.config/i3/scripts/bandwidth
interval=persist
min_width=100
background=#292e42

[simple-2]
full_text=  
background=#292e42
min_width=20

[simple-2]
full_text=  
min_width=20

[time]
label=<span font='FontAwesome' size='large'>  </span>
command=date '+%a %d %b  %H:%M'
interval=10
align=right
min_width=110

[simple-2]
full_text=  
min_width=10
# vim: ft=dosini
