# Font ligatures settings for Jet Brains Mono Font:
# https://github.com/JetBrains/JetBrainsMono/wiki/OpenType-features
font_family      family='JetBrainsMono Nerd Font Mono' style=Light features='+zero'
bold_font        family='JetBrainsMono Nerd Font Mono' style=Bold features='+zero'
italic_font      family='JetBrainsMono Nerd Font Mono' style='Light Italic' features='+zero'
bold_italic_font family='JetBrainsMono Nerd Font Mono' style='Bold Italic' features='+zero'
font_size        11.0
modify_font cell_height 110%

symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF,U+100000-U+10ffff JetBrainsMonoNL Nerd Font