# monitors
set $left_mon HDMI-0
set $right_mon DP-0

##########################################
# configuration for workspace behaviour: #
##########################################

workspace_layout default

# define monitor bindings to workspaces
# development
workspace 1 output $left_mon
# file manager
workspace 2 output $left_mon
# slack
workspace 3 output $left_mon
# web browser
workspace 4 output $right_mon
# tg
workspace 5 output $right_mon
# zoom
workspace 6 output $right_mon
# music
workspace 7 output $right_mon

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1:"
set $ws2 "2:"
set $ws3 "3:"
set $ws4 "4:"
set $ws5 "5:"
set $ws6 "6:"
set $ws7 "7:"

# bind program to workspace and focus to them on startup:
assign [class="kitty"] $ws1
assign [class="(?i)firefox"] $ws4
assign [class="Thunar"] $ws2
assign [class="TelegramDesktop"] $ws5
assign [class="Slack"] $ws3
assign [class="zoom"] $ws6
assign [class="Spotify"] $ws7
assign [class="code"] $ws1
assign [class="jetbrains-rider"] $ws1

# automatic set focus new window if it opens on another workspace than the current:
for_window [class=kitty] focus
for_window [class=(?i)firefox] focus
for_window [class=Thunar] focus
for_window [class=Thunderbird] focus
for_window [class=zoom] focus
for_window [class=Spotify] focus

# keybindings
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7

# move window to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
